name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "38 7,9,11,14 * * *" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "kevinotuteye@gmail.com"
          git config --local user.name "knotuteye"
          git add -A
          
          arr[0]="kno: hash regex"
          arr[1]="kno: reverse refactor"
          arr[2]="bugfix: enhance datetime render"
          arr[3]="hotfix: hook call fix"
          arr[4]="bot reset auto date"
          arr[5]="finished api rewrite"
          arr[6]="kno: finish reset"
          arr[7]="kno: cron commit"
          arr[8]="kno: disable UTC"
          arr[9]="kno: flag excessive calls"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
